// API "goa Swagger service": Application Resource Href Factories
//
// Code generated by goagen v1.1.0, DO NOT EDIT.
//
// Command:
// $ goagen
// --design=github.com/goadesign/swagger-service/design
// --out=$(GOPATH)/src/github.com/goadesign/swagger-service
// --version=v1.1.0

package app

// SpecHref returns the resource href.
func SpecHref() string {
	return "/swagger/spec"
}
